# Generated by Django 5.0.4 on 2024-04-30 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bien_immobilier',
            fields=[
                ('id_bien', models.AutoField(primary_key=True, serialize=False)),
                ('type_bien', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('nombre_chambre', models.CharField(max_length=200)),
                ('prix', models.FloatField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id_locataire', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('coordonnees', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id_proprietaire', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('coordonnees', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeReparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('etat_demande', models.CharField(max_length=100)),
                ('bien_immobilier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biens_immobiliers.bien_immobilier')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biens_immobiliers.locataire')),
            ],
        ),
        migrations.CreateModel(
            name='ContratLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_bail', models.PositiveIntegerField()),
                ('loyer_mensuel', models.FloatField()),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(auto_now_add=True)),
                ('bien_immobilier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biens_immobiliers.bien_immobilier')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biens_immobiliers.locataire')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(max_length=100)),
                ('contrat_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biens_immobiliers.contratlocation')),
            ],
        ),
    ]
